spring.application.name=cleanarchitecture

server.port=8080

# Connection DB
spring.datasource.url=jdbc:postgresql://localhost:5432/clean_architecture
spring.datasource.username=postgres
spring.datasource.password=MySecretPassword
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
