spring.application.name=cleanarchitecture

server.port=8080

# Connection DB
spring.datasource.url=jdbc:postgresql://localhost:5432/clean_architecture_db
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
